spring:
  application:
    name: prime-properties-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/prime_properties
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.primeproperties: DEBUG
    org.springframework.security: DEBUG
